name: Deploy da Aplicação Angular

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o ambiente Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
    
      - name: Run tests
        run: npm run test
    
      - name: Build
        run: npm run build

